export default {
    // BUSINESS
    RENDER_FETCHED_BUSINESSES: 'RENDER_FETCHED_BUSINESSES',
    INIT_BUSINESSES_STATE: 'INIT_BUSINESSES_STATE',
    // AUTH
    LOGIN_USER: 'LOGIN_USER',
    // LAYOUT
    INIT_LAYOUT_STATE: 'INIT_LAYOUT_STATE',
    TOGGLE_SIDE_DRAWER: 'TOGGLE_SIDE_DRAWER',
    TOGGLE_GETTING_STARTED: 'TOGGLE_GETTING_STARTED',
    LOGOUT_USER: 'LOGOUT_USER'
}
