export default {
    // BUSINESS
    RENDER_FETCHED_BUSINESSES: 'RENDER_FETCHED_BUSINESSES',
    INIT_BUSINESSES_STATE: 'INIT_BUSINESSES_STATE',
    // AUTH
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    // LAYOUT
    INIT_LAYOUT_STATE: 'INIT_LAYOUT_STATE',
    TOGGLE_SIDE_DRAWER: 'TOGGLE_SIDE_DRAWER',
    TOGGLE_GETTING_STARTED: 'TOGGLE_GETTING_STARTED',
    TOGGLE_REGISTERING_BUSINESS: 'TOGGLE_REGISTERING_BUSINESS',
    // SEARCH
    INIT_SEARCH_STATE: 'INIT_SEARCH_STATE',
    SEARCH_NAME: 'SEARCH_NAME',
    // FILTER
    INIT_FILTER_TOOLS_STATE: 'INIT_FILTER_TOOLS_STATE'
}
